# Generated by Django 5.2 on 2025-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('classification', models.CharField(choices=[('animals', 'Животные'), ('hostile', 'Враждебные мобы'), ('neutral', 'Нейтральные мобы'), ('npc', 'Мирные NPC'), ('main', 'Главный персонаж'), ('boss', 'Босс-мобы')], default='neutral', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('special_information', models.TextField()),
            ],
        ),
    ]
